### ISSUE TITLE
Mesh Ai with API WhatsApp

### ISSUE THREAD

**Issue by brauliodiasribeiro** [chasebank87/mesh-ai#13]
I would like to use Fabric AI in an API WhatsApp. When user sends a message, it sends the command to Mesh AI. Would it be possible to modify this plugin to adapt it. Since I don't have much knowledge, could you give me a little tip to get started? I need to understand how to call Mesh AI in the API.

Tks

**Comment by chasebank87** [comment]
This would entail creating a new plugin, that is installed alongside mesh-ai however I have not designed my plugin in a way that other plugins can use easily right now. It can be done im sure of that but not straight forward. May I ask what you are trying to accomplish in detail?

**Comment by brauliodiasribeiro** [comment]
I'm trying to read my markdown documents with AI and answer questions.

But I thought using fabric ai prompts to do this.
Because the prompts are markeddown and the community is always creating new ones.

**Comment by chasebank87** [comment]
But how does WhatsApp come in to play?Sent from my iPhoneOn Sep 21, 2024, at 11:31 PM, Braulio Dias Ribeiro ***@***.***> wrote:﻿
I'm trying to read my markdown documents with AI and answer questions.
But I thought using fabric ai prompts to do this.
Because the prompts are markeddown and the community is always creating new ones.

**Comment by brauliodiasribeiro** [comment]
> But how does WhatsApp come in to play?Sent from my iPhoneOn Sep 21, 2024, at 11:31 PM, Braulio Dias Ribeiro ***@***.***> wrote:﻿ I'm trying to read my markdown documents with AI and answer questions. But I thought using fabric ai prompts to do this. Because the prompts are markeddown and the community is always creating new ones. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

When I receive a message on WhatsApp (Evolution API), I need to send a command to run some Fabric AI prompt. The problem is that I don't know how to do this. Your plugin doesn't need to have Fabric installed, so I think it searches directly in the Fabric GitHub prompts. 

Maybe I need to use LangFlow to create a chatbot and connect with Fabric AI (similar to your obsidian plugin). I'm still researching this.

**Comment by chasebank87** [comment]
Gotcha, all I do to get the patterns is download them to file from the fabric github repo. You probably could do that in Langflow, never used it.Sent from my iPhoneOn Sep 22, 2024, at 12:20 AM, Braulio Dias Ribeiro ***@***.***> wrote:﻿

But how does WhatsApp come in to play?Sent from my iPhoneOn Sep 21, 2024, at 11:31 PM, Braulio Dias Ribeiro @.> wrote:﻿ I'm trying to read my markdown documents with AI and answer questions. But I thought using fabric ai prompts to do this. Because the prompts are markeddown and the community is always creating new ones. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.>

When I receive a message on WhatsApp (Evolution API), I need to send a command to run some Fabric AI prompt. The problem is that I don't know how to do this. Your plugin doesn't need to have Fabric installed, so I think it searches directly in the Fabric GitHub prompts.
Maybe I need to use LangFlow to create a chatbot and connect with Fabric AI (similar to your obsidian plugin). I'm still researching this.

**Comment by brauliodiasribeiro** [comment]
> Gotcha, all I do to get the patterns is download them to file from the fabric github repo. You probably could do that in Langflow, never used it.Sent from my iPhoneOn Sep 22, 2024, at 12:20 AM, Braulio Dias Ribeiro ***@***.***> wrote:﻿ But how does WhatsApp come in to play?Sent from my iPhoneOn Sep 21, 2024, at 11:31 PM, Braulio Dias Ribeiro @.> wrote:﻿ I'm trying to read my markdown documents with AI and answer questions. But I thought using fabric ai prompts to do this. Because the prompts are markeddown and the community is always creating new ones. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.> When I receive a message on WhatsApp (Evolution API), I need to send a command to run some Fabric AI prompt. The problem is that I don't know how to do this. Your plugin doesn't need to have Fabric installed, so I think it searches directly in the Fabric GitHub prompts. Maybe I need to use LangFlow to create a chatbot and connect with Fabric AI (similar to your obsidian plugin). I'm still researching this. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

I’m going to try… tks
