### ISSUE TITLE
Error path source

### ISSUE THREAD

**Issue by brauliodiasribeiro** [chasebank87/mesh-ai#7]
Any sugestion? Tks
![01](https://github.com/user-attachments/assets/8e9f2fe0-9045-4904-b3ec-77180263a93f)
![02](https://github.com/user-attachments/assets/e467813d-b718-4e09-a6a2-fa3d13bf5a75)

**Comment by chasebank87** [comment]
Forward slashes?Sent from my iPhoneOn Sep 13, 2024, at 5:38 PM, Braulio Dias Ribeiro ***@***.***> wrote:﻿
Any sugestion? Tks
01.png (view on web)
02.png (view on web)

**Comment by brauliodiasribeiro** [comment]
> Forward slashes?Sent from my iPhoneOn Sep 13, 2024, at 5:38 PM, Braulio Dias Ribeiro ***@***.***> wrote:﻿ Any sugestion? Tks 01.png (view on web) 02.png (view on web) —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

I can't believe it! How could I have been blind? lol
Thank you very much

Now it works, but after I click on the button, the button no longer appears
![image](https://github.com/user-attachments/assets/39d5acb2-7f8d-4c6e-86a7-2d4bf3dc2d2d)

**Comment by chasebank87** [comment]
Can you try dark mode and tell me if it still happens? Sent from my iPhoneOn Sep 14, 2024, at 6:11 AM, Braulio Dias Ribeiro ***@***.***> wrote:﻿

Forward slashes?Sent from my iPhoneOn Sep 13, 2024, at 5:38 PM, Braulio Dias Ribeiro @.> wrote:﻿ Any sugestion? Tks 01.png (view on web) 02.png (view on web) —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: @.>

I can't believe it! How could I have been blind? lol
Thank you very much
Now it works, but after I click on the button, the button no longer appears
image.png (view on web)

**Comment by brauliodiasribeiro** [comment]
> Can you try dark mode and tell me if it still happens? Sent from my iPhoneOn Sep 14, 2024, at 6:11 AM, Braulio Dias Ribeiro ***@***.***> wrote:﻿ Forward slashes?Sent from my iPhoneOn Sep 13, 2024, at 5:38 PM, Braulio Dias Ribeiro @.> wrote:﻿ Any sugestion? Tks 01.png (view on web) 02.png (view on web) —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: @.> I can't believe it! How could I have been blind? lol Thank you very much Now it works, but after I click on the button, the button no longer appears image.png (view on web) —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

Keep going .... Maybe the problem is here.
![image](https://github.com/user-attachments/assets/4c12fcc0-2c69-4ae6-a27b-4f1534578cdc)

**Comment by chasebank87** [comment]
Sorry you did find a bug for me so that is fixed in version 1.0.5 where on light mode the button text isnt visible. With the processing continuing to run is most likely an issue with your setup. If you could, go into the plugin settings and turn on debug mode, then open up developer tools and see what errors or logs you get when you try to run. Post them here and I will help you out.

**Comment by chasebank87** [comment]
Also before you do anything switch to version 1.0.5 this is the most up to date version. the higher versions are currently out of date because of the official release merge process.

**Comment by brauliodiasribeiro** [comment]
I went back to version 1.0.5 and it worked.

I don't know how to debug, sorry.
I saw on google that I need to press ctrl+shift+I.
I just don't know how to export the debugging result.

If you need debugging, let me know and I'll try to figure out how to export it
Thank you for your help, and thank you for your time. This plugin and this AI is sensational.

**Comment by chasebank87** [comment]
Great thanks,In the future for other issues, the plugin settings has a debug option at the bottom. Once it’s enabled the developer tools, go to view, toggle developer tools.Then open console, and copy paste the logs.Sent from my iPhoneOn Sep 16, 2024, at 10:52 AM, Braulio Dias Ribeiro ***@***.***> wrote:﻿
I went back to version 1.0.5 and it worked.
I don't know how to debug, sorry.
I saw on google that I need to press ctrl+shift+I.
I just don't know how to export the debugging result.
If you need debugging, let me know and I'll try to figure out how to export it
Thank you for your help, and thank you for your time. This plugin and this AI is sensational.
